config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'home/index'
  get 'home/show'
  post 'home/buynow'
  get 'admin/index'
  post 'admin/update'
  root to: "welcome#index"
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  devise_for :admins, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }  

     resources :products

end

app/views/admin/index.html.erb
<% if admin_signed_in? %>
<div class="row">
	<div class="col-sm-12">
		<h1>Listing Products</h1>
		<table class="table">
		  <tr>
		    <th>Photo</th>
		    <th>Title</th>
		    <th>Description</th>
		    <th>Unit Price</th>
		    <th>Stock</th>
		    <th>Promotion %</th>
		    <th>Start</th>
		    <th>End</th>
		    <th>Action</th>
		  </tr>
		 
		  <% @products.each do |product| %>
		    <tr>
		      <td><%=image_tag product.image, :class=>"img-responsive", :style=>"height:80px;" %></td>
		      <td><%= product.title %></td>
		      <td><%= product.description %></td>
		      <td><%= product.unitprice %></td>
		      <td><%= product.stock %></td>
		      <%= form_for :product, url: admin_update_path do |f| %>
		      <%= f.hidden_field:id, :value=>product.id %>
		      <td><%= f.text_field:promotion, :value=>product.promotion, :class=>"form-control" %></td>
		      <td><%= f.text_field:p_start, :value=>product.p_start, :class=>"form-control", :id=>"datetimepicker1"+product.id.to_s %></td>
		      <td><%= f.text_field:p_end, :value=>product.p_end, :class=>"form-control", :id=>"datetimepicker2"+product.id.to_s %></td>
		    	<td><%= f.submit "update", :class=>'btn btn-primary' %></td>			
				<% end %>		    
		    </tr>
		  <% end %>
		</table>
	</div>
</div>
<% else %>
<div class="row">
	<div class="col-sm-12">
		<h1>Hello!</h1>
	</div>
</div>
<% end %>

<% content_for :foot do %>
	<script>
	
	$(document).ready(function(){
	var $j = jQuery.noConflict();
	<% @products.each do |product| %>	
	$j('#datetimepicker1<%= product.id %>').datetimepicker();
	$j('#datetimepicker2<%= product.id %>').datetimepicker();	
	<% end %>
	});
	</script>
<% end %>