config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'home/index'
  get 'home/show'
  post 'home/buynow'
  get 'admin/index'
  post 'admin/update'
  root to: "welcome#index"
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  devise_for :admins, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }  

     resources :products

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index 
  if current_user
     @products = Product.where("promotion>0").where("stock>0").where("p_end>=?",Time.now).where("user_id!=?",current_user.id)
   else
     redirect_to new_user_session_path, notice: 'You are not logged in.'
   end
  end
  
  def show 
  if current_user
     @orders =Order.includes(:product).where("user_id=?",current_user.id)
     render 'index'
   else
     redirect_to new_user_session_path, notice: 'You are not logged in.'
   end
  end
  
  def buynow
  	     @product = Product.find(params[:id])
		  
		 if @product
		    @discount = @product.unitprice*(100-@product.promotion)/100
        if current_user.credits>= @discount
          @newOrder = @product.orders.create({user_id:current_user.id,price:@discount})
          @remaincredits = current_user.credits-@discount
          if current_user.update({credits:@remaincredits})
            @remainstock = @product.stock-1
          	@product.update({stock:@remainstock})
            redirect_to home_index_path
          else
            @newOrder.destroy()
            redirect_to home_index_path
          end
        else
          redirect_to home_index_path
        end 
	    else
	      redirect_to home_index_path
	    end 
		 
  	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>

<% if @products %>
<div class="row">
<% @products.each do |product| %>
	<div class="col-sm-4 text-center" style="height:500px">
	<div class="panel panel-default">
		<div class="panel-body">
		      <h2><%= product.title %></h2>
		    	<%=image_tag product.image, :class=>"img-responsive img-thumbnail" %>
		    	<br/>
				<div class="row">	
					<div class="col-sm-12 padtp10">    	
				    	<span class="price pull-left"> <s><%= product.unitprice %></s><small>THB</small></span> 
				    	<span class="sale pull-left"><%= product.unitprice*(100-product.promotion)/100 %> </span>	    	
						<span class="promo badge pull-right">- <%= product.promotion %>%</span>
					</div>
				</div>
				<h4 class="blue">Before: <%= product.p_end.to_time.strftime('%a %b %d, %Y %H:%M:%S') %></h4>
				only <%= product.stock %> Left <br/>
				<%= form_for :buynow, url: home_buynow_path do |f| %>
				<input type="hidden" name="id" value="<%= product.id %>">
				<button class="btn btn-danger btn-buy">BUY NOW</button>
				<% end %>
		</div>
	</div>
 	</div>

<% end %>
</div>

<% elsif @orders %>
<div class="row">
	<div class="col-sm-12">
	  <table class="table">
	    <tr>
	    	<th>Product ID : Title </th>
	    	<th>Price</th>
	    	<th>QTY</th>
	    	<th>Date</th>
	    </tr>
	    <% @orders.each do |order|%>
	    <tr>
	    	<td>#<%= order.product_id%> : <%= order.product.title%></td>
	    	<td><%= order.price%></td>
	    	<td><%= order.qty%></td>
	    	<td><%= order.created_at.to_time.strftime('%a %b %d, %Y %H:%M:%S')%></td>
	    </tr>
	   <% end %>
	  </table>		
	</div>
</div>
<% end %>
<% end %>