config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'home/index'
  get 'home/show'
  post 'home/buynow'
  get 'admin/index'
  post 'admin/update'
  root to: "welcome#index"
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  devise_for :admins, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }  

     resources :products

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="container">
<nav class="navbar navbar-default container" role="navigation"">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-mk-navbar-collapse-1">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a href="/" class="navbar-brand">E commerce</a>

        </div>

        <div class="collapse navbar-collapse" id="bs-mk-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <% if admin_signed_in? %>
                <li><a  href="/admin/index">Dashboard</a></li>
                <% end %>
                
            </ul>
            <ul class="nav navbar-nav navbar-right">
                   <% if admin_signed_in? %>
						  <li>
						  <%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>        
						  </li>
						<% else %>
						  <li>
						  <%= link_to('Login', new_admin_session_path)  %>  
						  </li>
						  <li>
						  <%= link_to('Sign up', new_admin_registration_path) %>  
						  </li>
						<% end %>                      
            </ul>
        </div>
    </div>
</nav>
</header>
<div class="container">
	<%= yield %>
</div>
<%= javascript_include_tag "application" %>
<%= yield :foot %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="container">
<nav class="navbar navbar-default container" role="navigation"">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-mk-navbar-collapse-1">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a href="/" class="navbar-brand">E commerce</a>

        </div>

        <div class="collapse navbar-collapse" id="bs-mk-navbar-collapse-1">
            <ul class="nav navbar-nav">
            <% if user_signed_in? %>
                <li><a  href="/home/index">Home</a></li>
                <li><a  href="/products">Sell</a></li>
                <li><a  href="/home/show">Purchased Items</a></li>                
            <% end %> 
                
            </ul>
            <ul class="nav navbar-nav navbar-right">
                   <% if user_signed_in? %>
                   <li>
						  <a href="#">Credits : <%= current_user.credits %></a>        
						  </li>
						  <li>
						  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
						  </li>
						<% else %>
						  <li>
						  <%= link_to('Login', new_user_session_path)  %>  
						  </li>
						  <li>
						  <%= link_to('Sign up', new_user_registration_path) %>  
						  </li>
						<% end %>                      
            </ul>
        </div>
    </div>
</nav>
</header>
<div class="container">
	<%= yield %>
</div>
<%= javascript_include_tag "application" %>
<%= yield :foot %>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row padtp50">
<div class="col-sm-4"></div>
  <div class="col-sm-4">
		<%= yield %>
	</div>
<div class="col-sm-4"></div>
</div>
</body>
</html>